public enum EODisplayType {
   START,
   CREATEARRANGEMENT,
   UPDATEARRANGEMENT,
   DELETEARRANGEMENT,
   OPENARRANGEMENT,
   CREATEEVENT,
   UPDATEEVENT,
   DELETEEVENT,   
   EXPORT,
   IMPORT,
   ADMFACILITATOR,
   ERROR,
   ADMEVENTTYPE;
}