-- MySQL Script generated by MySQL Workbench
-- Fri Nov 23 13:17:36 2018
-- Model: PlanOrg    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `planOrg` DEFAULT CHARACTER SET utf8 ;
USE `planOrg` ;

-- -----------------------------------------------------
-- Table `mydb`.`EOCustomerContactInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `planOrg`.`EOCustomerContactInfo` (
  `idEOContactInfo` INT NOT NULL,
  `deletedStatus` TINYINT NULL,
  `name` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `email` VARCHAR(255) NULL,
  `info` VARCHAR(1000) NULL,
  `company` VARCHAR(255) NULL,
  PRIMARY KEY (`idEOContactInfo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EOArrangements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `planOrg`.`EOArrangements` (
  `idEOArrangements` INT NOT NULL,
  `EOCustomerContactInfo_idEOContactInfo` INT NULL,
  `name` VARCHAR(500) NULL,
  `description` TEXT(1000) NULL,
  `dateTimeStart` DATETIME NULL,
  `dateTimeEnd` DATETIME NULL,
  `price` INT NULL,
  PRIMARY KEY (`idEOArrangements`),
  INDEX `fk_EOArrangements_EOCustomerContactInfo_idx` (`EOCustomerContactInfo_idEOContactInfo` ASC),
  CONSTRAINT `fk_EOArrangements_EOCustomerContactInfo`
    FOREIGN KEY (`EOCustomerContactInfo_idEOContactInfo`)
    REFERENCES `planOrg`.`EOCustomerContactInfo` (`idEOContactInfo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EOEvents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `planOrg`.`EOEvents` (
  `idEOEvents` INT NOT NULL,
  `EOArrangements_idEOArrangements` INT NULL,
  `description` VARCHAR(1000) NULL,
  `dateTimeStart` VARCHAR(45) NULL,
  `dateTimeEnd` VARCHAR(45) NULL,
  `price` DOUBLE NULL,
  PRIMARY KEY (`idEOEvents`),
  INDEX `fk_EOEvents_EOArrangements1_idx` (`EOArrangements_idEOArrangements` ASC),
  CONSTRAINT `fk_EOEvents_EOArrangements1`
    FOREIGN KEY (`EOArrangements_idEOArrangements`)
    REFERENCES `planOrg`.`EOArrangements` (`idEOArrangements`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EOEventtypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `planOrg`.`EOEventtypes` (
  `idEOEventtypes` INT NOT NULL,
  `deletedStatus` TINYINT NULL,
  `EOEvents_idEOEvents` INT NULL,
  `name` VARCHAR(500) NULL,
  `description` VARCHAR(1000) NULL,
  `locationStart` VARCHAR(500) NULL,
  `locationEnd` VARCHAR(500) NULL,
  `time` TIME NULL,
  `price` DOUBLE NULL,
  PRIMARY KEY (`idEOEventtypes`),
  INDEX `fk_EOEventtypes_EOEvents1_idx` (`EOEvents_idEOEvents` ASC),
  CONSTRAINT `fk_EOEventtypes_EOEvents1`
    FOREIGN KEY (`EOEvents_idEOEvents`)
    REFERENCES `planOrg`.`EOEvents` (`idEOEvents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EOExternalContactInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `planOrg`.`EOExternalContactInfo` (
  `idEOContactInfo` INT NOT NULL,
  `deletedStatus` TINYINT NULL,
  `name` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `email` VARCHAR(255) NULL,
  `info` VARCHAR(1000) NULL,
  `company` VARCHAR(255) NULL,
  PRIMARY KEY (`idEOContactInfo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EOFacilitatorContactInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `planOrg`.`EOFacilitatorContactInfo` (
  `idEOContactInfo` INT NOT NULL,
  `deletedStatus` TINYINT NULL,
  `name` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `email` VARCHAR(255) NULL,
  `info` VARCHAR(1000) NULL,
  `company` VARCHAR(255) NULL,
  `EOArrangements_idEOArrangements` INT NOT NULL,
  PRIMARY KEY (`idEOContactInfo`),
  INDEX `fk_EOFacilitatorContactInfo_EOArrangements1_idx` (`EOArrangements_idEOArrangements` ASC),
  CONSTRAINT `fk_EOFacilitatorContactInfo_EOArrangements1`
    FOREIGN KEY (`EOArrangements_idEOArrangements`)
    REFERENCES `planOrg`.`EOArrangements` (`idEOArrangements`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
